### ISSUE TITLE
Bash скрипт для отправки работы на проверку

### ISSUE THREAD

**Issue by zmm** [EduardBlees/Master-s-thesis#103]
Необходимо подготовить bash скрипт, который проделает следующие шаги:
- отправит на проверку файл работы с необходимыми параметрами
- дождется, когда система проверит решение (или выбросить ошибку при истечении таймаута)
- выведет ссылку на страницу проверки

Аргументы:
- файл работы на проверку
- адрес сервиса
- название критерия для проверки
- файл-название работы

**Comment by levi218** [comment]
python или selenium разрешен или только bash?

**Comment by zmm** [comment]
Лучше использовать чистый bash - предполагается, что скрипт будет запускаться в очень ограниченной среде с точки зрения ресурсов. 
Если для удобства работы нужны дополнительные веб-интерфейсе в самом сервисе, то добавьте их.

Также скорректировал список аргументов - убрал отдельно ключевые слова.
