### ISSUE TITLE
Критерий проверки "Упоминание ключевых слов"

### ISSUE THREAD

**Issue by zmm** [EduardBlees/Master-s-thesis#104]
Необходимо создать критерий по аналогии с существующими :
- детектировать в тексте список ключевых слов, распарсить
- проверить, что каждый элемент списка упоминается хотя бы один раз в тексте работы (Помимо самого списка)

Если в тексте работы нет списка ключевых слов - считаем, что критерий завален.

**Comment by levi218** [comment]
список ключевых слов, представленных в графическом интерфейсе или в самом тексте?
если в самом тексте, если возможно, можете ли вы предоставить мне файл примера?

**Comment by zmm** [comment]
Давайте считать, что список ключевых слов берем из текста. 

Примеры приложил

https://github.com/moevm/scientific_writing-2019/blob/master/6303_KutsenokLA/paper.pdf
https://github.com/moevm/scientific_writing-2019/blob/master/6303_VaganovNA/paper.pdf

Предлагаю использовать простое регулярное выражение для поиска такого шаблона
