### ISSUE TITLE
SW скрипт - избавиться от промежуточных статусов

### ISSUE THREAD

**Issue by zmm** [EduardBlees/Master-s-thesis#11]
Идея: давайте сделаем отдельное CSV-представление с суммарными результатом по каждому заданию (но старое тоже оставим, чтобы все желающие могли убедиться в честности оценки)

**Comment by EduardBlees** [comment]
@zmm, как это должно выглядеть?

**Comment by zmm** [comment]
Идея такая - пусть будет отдельный CSV c колонками:
ФИО, Фактический результат, Ответы на ключевые вопросы, Обзор аналогов, ...(колонка == название задания из http://se.moevm.info/doku.php/staff:courses:sci_writing:plan), Сумма оценок

**Comment by EduardBlees** [comment]
[Commit](https://github.com/EduardBlees/Master-s-thesis/commit/0434297f274a3a6ebf99c3cf3d010f9ecaa12222)

**Comment by EduardBlees** [comment]
Объеденить 2-3 колонки

**Comment by EduardBlees** [comment]
[Commit](https://github.com/EduardBlees/Master-s-thesis/commit/015a778200b2269469adb0ab328cc65d9ea0bc6e)
