### ISSUE TITLE
github action для проверки первого задания из https://github.com/moevm/scientific_writing-2020

### ISSUE THREAD

**Issue by zmm** [EduardBlees/Master-s-thesis#120]
Необходимо выполнить следующие проверки
- проверка того, что ветка синхронизирована с master и нет конфликтов
- пользователь работает только с одним каталогом и этот каталог называется правильно
- присутствуют все необходимые файлы (http://se.moevm.info/doku.php/staff:courses:sci_writing:plan#%D0%B7%D0%B0%D0%B4%D0%B0%D0%BD%D0%B8%D0%B5_1_-_%D0%B2%D1%8B%D0%B1%D0%BE%D1%80_%D1%82%D0%B5%D0%BC%D1%8B_%D0%B8_%D0%BE%D1%82%D0%B2%D0%B5%D1%82%D1%8B_%D0%BD%D0%B0_%D0%BA%D0%BB%D1%8E%D1%87%D0%B5%D0%B2%D1%8B%D0%B5_%D0%B2%D0%BE%D0%BF%D1%80%D0%BE%D1%81%D1%8B_%D0%B4%D0%BE_011120)
- заглушку для будущей отправки материалов в сервис проверки (пока можно поставить просто пустой шаг)

Если проверка не прошла, то необходимо добавить к PR комментарий с описанием проблемы, а также метку "Actions required"

Для тестов создайте отдельный репо - после проверки я перенесу action в репозиторий курса

**Comment by levi218** [comment]
Example over here https://github.com/levi218/scientific-writing-gh-actions-example
