### ISSUE TITLE
Эксперименты на "Корчевателе" и похожих вещах

### ISSUE THREAD

**Issue by zmm** [EduardBlees/Master-s-thesis#30]
Мы с вами разрабатываем инструмент, выполняющий проверку необходимых условий качества статьи. Поэтому полезно было бы поизмерять абсолютно бредовую статью, чтобы показать, что именно наши критерии оценивают https://ru.wikipedia.org/wiki/%D0%9A%D0%BE%D1%80%D1%87%D0%B5%D0%B2%D0%B0%D1%82%D0%B5%D0%BB%D1%8C_(%D1%81%D1%82%D0%B0%D1%82%D1%8C%D1%8F)

**Comment by EduardBlees** [comment]
Здравствуйте. Мне не удалось найти альтернативу, куда можно подать статью. Есть ли возможность рассмотреть вариант с бакалавром? И что до какого числа должен сделать я?

Eduard Blees

From: Mark Zaslavskiy
Sent: 20 марта 2018 г. 12:24
To: EduardBlees/Master-s-thesis
Cc: Subscribed
Subject: [EduardBlees/Master-s-thesis] Эксперименты на "Корчевателе" и похожих вещах (#30)

Мы с вами разрабатываем инструмент, выполняющий проверку необходимых условий качества статьи. Поэтому полезно было бы поизмерять абсолютно бредовую статью, чтобы показать, что именно наши критерии оценивают https://ru.wikipedia.org/wiki/%D0%9A%D0%BE%D1%80%D1%87%D0%B5%D0%B2%D0%B0%D1%82%D0%B5%D0%BB%D1%8C_(%D1%81%D1%82%D0%B0%D1%82%D1%8C%D1%8F)

**Comment by EduardBlees** [comment]
[Commit](https://github.com/EduardBlees/Master-s-thesis/commit/28f35576e303849c48548828ec4f9c8f55ca4c32)
