### ISSUE TITLE
Слой абстракции от формата файла

### ISSUE THREAD

**Issue by zmm** [EduardBlees/Master-s-thesis#49]

**Comment by vjkuznetsov** [comment]
Марк, требуется отдельный слой?

Насколько я понял (поправьте меня, если я не прав, пожалуйста), анализ производится на списке строк, то есть сам анализ уже независим от формата файла. 

Процесс извлечения текста из файла уже инкапсулирован в интерфейсе ITextExtractor (в настоящий момент есть только одна его реализация PdfTextExtractor). Достаточно дописать TextExtractor для других требуемых форматов (точнее, переиспользовать существующие решения) и добавить в HomeController.AnalyzePaper полиморфный вызов нужного класса, реализующего ITextExctractor, в зависимости от расширения файла
