### ISSUE TITLE
Визуальная подсветка ключевых слов, слов из названия в тексте работы

### ISSUE THREAD

**Issue by zmm** [EduardBlees/Master-s-thesis#76]
На странице с результатами проверки статьи необходимо по нажатию подсвечивать в тексте работы все слова из : 
- списка ключевых слов
- названия работы

Как это должно работать:
- Список ключевых слов и название работы необходимо вывести над текстом работы
- при нажатии на каждое из слов в названии / каждого элемента ключевых слов необходимо подсветить цветом каждое вхождение в тексте (вне зависимости от словоформы).

**Comment by levi218** [comment]
Список ключевых слов из графического интерфейса никогда не отправлялся на контроллер или серверную часть. (JavaScript-код в конце Index.cshtml)
Реализация включена в этот issue?

**Comment by zmm** [comment]
Хорошее замечание!

Давайте добавим такую реализацию, но будем учитывать и ключевые слова найденные в тексте (https://github.com/OSLL/sw-auto/issues/104). Порядок такой:
- если в тексте найден список ключевых слов, то подсвечиваем их
- если в тексте не найден список ключевых слов, то подсвечиваем ключевые слова из графического интерфейса
