### ISSUE TITLE
Указывать при создании критерия допустимые диапазоны для полей (вес и штраф)

### ISSUE THREAD

**Issue by zmm** [EduardBlees/Master-s-thesis#92]
Укажите текстом на веб-странице создания критерия:
- в каком диапазоне могут быть веса и штрафы 
- добавьте js валидацию и не сохраняйте заведомо кривые критерии (например с нулевой макс. оценкой)

**Comment by levi218** [comment]
довольно глупый вопрос, но в каком диапазоне могут быть веса и штрафы? вес в диапазоне (0,1) а штраф в (0, максимальная оценка)?

**Comment by zmm** [comment]
Это на самом деле хороший вопрос! 

Общая оценка в рамках каждого критерия задается параметром "Максимальная оценка за статью", поэтому, с точки зрения логики, все критерии не должны выходить за эти рамки суммой произведений "штраф * вес". 

Предлагаю вам также проконсультироватся у @vjkuznetsov - Владимир более погружен в технические детали.
